{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "clustercode.fullname" . }}
  labels:
    {{- include "clustercode.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "clustercode.fullname" . }}-manager
subjects:
- kind: ServiceAccount
  name: {{ include "clustercode.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
